In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as datetime



from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier, AdaBoostClassifier, StackingClassifier, RandomForestClassifier, BaggingClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support, balanced_accuracy_score, plot_precision_recall_curve, precision_recall_curve, precision_score, recall_score

from sklearn.model_selection import RandomizedSearchCV, train_test_split
import shap
import lightgbm as lgb 

pd.set_option('max_colwidth', 80)

In [8]:
df = pd.read_csv('final_data.csv') 
df.head()

TARGET_FID  Length  Install_year  Arterial_class  Surface_width  \
0           1  314.79          1972             2.0           40.0   
1           2  363.39          1972             0.0           46.0   
2           3  323.51          1972             0.0           46.0   
3           4  329.13          1928             0.0            0.0   
4           5  273.64          1928             2.0           42.0   

   Speed_limit  Slope  Width  Break_Yr  Target  ...  Surface_type_   \
0         25.0    0.0    8.0       NaN       0  ...               0   
1         20.0    4.0    8.0       NaN       0  ...               0   
2         20.0    4.0    8.0       NaN       0  ...               0   
3         20.0    6.0   12.0       NaN       0  ...               0   
4         25.0    4.0   18.0       NaN       0  ...               0   

   Surface_type_AC  Surface_type_AC/AC  Surface_type_AC/PCC  \
0                0                   0                    0   
1                1                   0                    0   
2                1                   0                    0   
3                0                   0                    0   
4                0                   0                    1   

   Surface_type_GRAVEL  Surface_type_PCC  Surface_type_ST  AGE  \
0                    0                 1                0   38   
1                    0                 0                0   38   
2                    0                 0                0   38   
3                    0                 0                1   82   
4                    0                 0                0   82   

   Nearby_breaks_1yr  Process_year  
0                  0          2010  
1                  0          2010  
2                  0          2010  
3                  0          2010  
4                  0          2010  

[5 rows x 56 columns]

In [9]:
df['Target'].unique()

array([0, 1])

In [10]:
df_2014 = df[df['Process_year'] == 2014]
df_2014.shape

(68274, 56)

In [11]:
df_2014['Break_Yr'].unique()

array([  nan, 2014.])

In [13]:
columns = df_2014.columns.drop(['TARGET_FID', 'Process_year', 'Break_Yr'])
df_2014_cols = df_2014[columns]
print(df_2014_cols.shape)
#df_2014_cols_cleaned = df_2014_cols[~df_2014_cols.isin([np.nan, np.inf, -np.inf]).any(1)].astype(np.float32) # removes rows with nan or inf points
df_2014_cols_cleaned = df_2014_cols.dropna(axis=0).astype(np.float32) # removes rows with nan or inf points
print(df_2014_cols_cleaned.shape)


(68274, 53)
(58917, 53)


In [15]:
features_df = df_2014_cols_cleaned.drop('Target', axis=1)
target_df = df_2014_cols_cleaned[['Target']]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(features_df, target_df, test_size=0.2, random_state=42)

In [19]:
etc = ExtraTreesClassifier()
etc.fit(X_train, y_train)


In [25]:
preds = etc.predict(X_test)
bal_acc = balanced_accuracy_score(y_pred=preds, y_true=y_test)
recall = recall_score(y_true=y_test, y_pred=preds)
precision = precision_score(y_true=y_test, y_pred=preds)
print(bal_acc)
print(recall)
print(precision)

0.7653184419520738
0.5319148936170213
0.625


In [28]:
confusion_matrix(y_test, preds)

array([[11722,    15],
       [   22,    25]])